### ISSUE TITLE
Sign In 🐛

### ISSUE THREAD

**Issue by RafaelZasas** [RafaelZasas/intro-to-firebase#4]
Sign In  fails when user already has a linked O-Auth Account

**Comment by RafaelZasas** [comment]
![image](https://user-images.githubusercontent.com/42390827/99157873-b688fe00-2681-11eb-9bea-0ca7311749aa.png)

**Comment by ANDREYDEN** [comment]
This is interesting, because I can still not reproduce this on my machine... @RafaelZasas, can you try out the latest `feature/auth` branch?
