### ISSUE TITLE
I/flutter (15524): Error signing up: type 'List<Object?>' is not a subtype of type 'PigeonUserDetails?' in type cast

### ISSUE THREAD

**Issue by yashshinde9321** [RafaelZasas/intro-to-firebase#48]
hi broo !!!
i am getting this error in my fluter application can you help me in this error to solve 
i think this error is coming to all recent developer

**Comment by RafaelZasas** [comment]
It is a very strange issue that I have seen myself- You will need to run `flutter pub upgrade --major-versions`.

I believe flutter uses a package called Pigeon and there may be breaking changes that have only been resolved in the latest firebase flutter SDK's.
